# Generated by Django 4.0.5 on 2022-06-27 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strip',
            name='flight_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stripManagement.flightplan'),
        ),
    ]
